steps:
  - name: "gcr.io/cloud-builders/mvn"
    args: ["clean", "verify"]
    dir: "/workspace/"
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "functions",
        "deploy",
        "Test-CloudFunctions",
        "--trigger-http",
        "--allow-unauthenticated",
        "--runtime",
        "java11",
        "--entry-point",
        "com.functions.HelloWorld",
      ]
    dir: "/workspace/"
  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: "bash"
    args: [./trigger.sh]
  - name: 'bash'
    script: |
     npm install -g newman
     newman run -d example-csv-all-types.csv  CreateUSers.postman_collection.json
  
  
 
   
 
