steps:
- name: "gcr.io/cloud-builders/gcloud"
    entrypoint: "bash"
    args: [./trigger.sh]
- name: 'gcr.io/cloud-builders/npm'
  entrypoint: 'bash'
  args:
   - '-c'
   - |
     npm install -g newman
     newman run -d example-csv-all-types.csv  CreateUSers.postman_collection.json 
       
        